version = 5.6.0
archive_dir = /etc/letsencrypt/archive/statrix.app
cert = /etc/letsencrypt/live/statrix.app/cert.pem
privkey = /etc/letsencrypt/live/statrix.app/privkey.pem
chain = /etc/letsencrypt/live/statrix.app/chain.pem
fullchain = /etc/letsencrypt/live/statrix.app/fullchain.pem
[renewalparams]
account = 3fb9249bd70219a4054ca9fbbba2c267
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
statrix.app = /var/www/certbot
www.statrix.app = /var/www/certbot
